import { PdfData } from '../pdfTypes';
import { e, fmtDate } from './htmlUtils';
import { buildLineChartSvg, buildBarChartSvg } from './htmlUtils';

export function renderPage3(data: PdfData, pageNum: number, totalPages: number): string {
  const today = fmtDate();
  const CW = 634; // content width px

  // Chart data
  const trends = data.dailyTrends.slice(-30);
  const passRateValues = trends.map(d => d.passRate);
  const execValues = trends.map(d => d.execCount);
  const dateLabels = trends.map(d => {
    const dt = new Date(d.date);
    return `${dt.getMonth() + 1}/${dt.getDate()}`;
  });

  // Build pass rate chart
  const lineH = 140;
  const lineSvg = buildLineChartSvg(passRateValues, CW, lineH, 'rgb(99,102,241)', 0, 100);
  const xLabels = dateLabels.filter((_, i) => i % Math.max(1, Math.floor(dateLabels.length / 6)) === 0 || i === dateLabels.length - 1);

  // Build velocity chart
  const barH = 110;
  const barSvg = buildBarChartSvg(execValues, CW, barH, 'rgb(99,102,241)', 'rgb(245,158,11)');

  // WoW table
  const hasLastWeekData = data.weekComparison.some(w => w.lastWeek > 0);

  return `
<div class="pdf-header">
  <span class="logo">Testably</span>
  <span class="page-title">Quality Trends</span>
</div>

<div class="pdf-content">
  <div class="sec-title" style="margin-top:0;">Pass Rate Trend (Last ${trends.length} Days)</div>
  <div style="position:relative;margin-bottom:6px;">
    <div style="display:flex;justify-content:space-between;font-size:9px;color:rgb(100,116,139);margin-bottom:2px;">
      <span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span>
    </div>
    <div class="chart-area" style="height:${lineH}px;background:#fff;padding:0;">
      ${lineSvg}
    </div>
    ${trends.length > 1 ? `
    <div style="display:flex;justify-content:space-between;font-size:8px;color:rgb(100,116,139);margin-top:2px;">
      ${dateLabels.filter((_, i) => i % Math.max(1, Math.floor(dateLabels.length / 6)) === 0 || i === dateLabels.length - 1)
        .map(l => `<span>${l}</span>`).join('')}
    </div>` : ''}
  </div>

  <div class="sec-title">Week-over-Week Comparison</div>
  ${hasLastWeekData ? `
  <table class="pdf-table" style="margin-bottom:14px;">
    <thead><tr><th>Metric</th><th>This Week</th><th>Last Week</th><th>Change</th></tr></thead>
    <tbody>
      ${data.weekComparison.map(w => {
        const isRate = w.metric.includes('%') || w.metric.includes('Rate');
        const decimals = isRate ? 1 : 0;
        const suffix = isRate ? '%' : '';
        const changeColor = w.change === 0 ? 'rgb(100,116,139)' : w.change > 0 ? 'rgb(16,163,127)' : 'rgb(239,68,68)';
        const changeSym = w.change === 0 ? '—' : w.change > 0 ? `▲ ${Math.abs(w.change).toFixed(1)}` : `▼ ${Math.abs(w.change).toFixed(1)}`;
        return `<tr>
          <td>${e(w.metric)}</td>
          <td style="font-weight:600;">${w.thisWeek.toFixed(decimals)}${suffix}</td>
          <td>${w.lastWeek.toFixed(decimals)}${suffix}</td>
          <td style="color:${changeColor};font-weight:600;">${changeSym}</td>
        </tr>`;
      }).join('')}
    </tbody>
  </table>` : `
  <div style="background:rgb(248,250,252);border:1px solid rgb(226,232,240);border-radius:6px;padding:10px 16px;margin-bottom:14px;font-size:10px;color:rgb(100,116,139);">
    No previous week data available for comparison.
  </div>`}

  <div class="sec-title">Execution Velocity (TC/Day)</div>
  <div class="chart-area" style="height:${barH}px;background:#fff;padding:0;margin-bottom:8px;">
    ${barSvg}
  </div>
  ${trends.length > 1 ? `
  <div style="display:flex;justify-content:space-between;font-size:8px;color:rgb(100,116,139);">
    ${dateLabels.filter((_, i) => i % Math.max(1, Math.floor(dateLabels.length / 6)) === 0 || i === dateLabels.length - 1)
      .map(l => `<span>${l}</span>`).join('')}
  </div>
  <div style="font-size:9px;color:rgb(100,116,139);margin-top:4px;text-align:center;">
    <span style="border-bottom:2px dashed rgb(245,158,11);padding-bottom:1px;margin-right:8px;">── 7-day moving avg</span>
    <span style="color:rgb(99,102,241);">■ Daily executions</span>
  </div>` : ''}
</div>

<div class="pdf-footer">
  <span>${e(data.projectName)}</span>
  <span>Generated by Testably — ${today}</span>
  <span>Page ${pageNum} of ${totalPages}</span>
</div>`;
}
