import { PdfData } from '../pdfTypes';
import { e, priColor, priAbbr, fmtDate } from './htmlUtils';

export function renderPage6(data: PdfData, pageNum: number, totalPages: number): string {
  const today = fmtDate();

  const riskBadge = (risk: string) => {
    if (risk === 'high') return `<span class="badge badge-red">&#9632; High</span>`;
    if (risk === 'medium') return `<span class="badge badge-amber">&#9632; Medium</span>`;
    return `<span class="badge" style="background:rgb(255,251,235);color:rgb(245,158,11);">&#9632; Low</span>`;
  };

  const failCountColor = (n: number) =>
    n >= 5 ? 'rgb(239,68,68)' : n >= 3 ? 'rgb(249,115,22)' : 'rgb(15,23,42)';

  return `
<div class="pdf-header">
  <span class="logo">Testably</span>
  <span class="page-title">Risk Assessment</span>
</div>

<div class="pdf-content">
  <div class="sec-title" style="margin-top:0;">Top Failed Test Cases</div>
  <table class="pdf-table" style="margin-bottom:14px;font-size:10px;">
    <thead>
      <tr><th style="width:5%;">#</th><th style="width:12%;">TC ID</th><th style="width:40%;">Title</th><th style="width:16%;">Priority</th><th style="width:10%;">Fails</th><th style="width:17%;">Last Failed</th></tr>
    </thead>
    <tbody>
      ${data.failedTCs.slice(0, 10).map((tc, i) => {
        const rawTitle = tc.title || `TC-${String(tc.id).slice(0, 8)}`;
        const title = rawTitle.length > 36 ? rawTitle.slice(0, 33) + '...' : rawTitle;
        return `
      <tr>
        <td class="c-light">${i + 1}</td>
        <td style="font-size:9px;">${e((tc.id || '').slice(0, 12))}</td>
        <td>${e(title)}</td>
        <td>
          <span class="pri-dot" style="background:${priColor(tc.priority)};"></span>
          <span style="color:${priColor(tc.priority)};">${e(priAbbr(tc.priority))}</span>
        </td>
        <td style="font-weight:700;color:${failCountColor(tc.failCount)};">${tc.failCount}</td>
        <td class="c-light">${e(tc.lastFailedRelative)}</td>
      </tr>`;
      }).join('')}
    </tbody>
  </table>

  ${data.flakyTCs.length > 0 ? `
  <div class="sec-title">Flaky Test Cases</div>
  <table class="pdf-table" style="margin-bottom:14px;font-size:10px;">
    <thead>
      <tr><th style="width:14%;">TC ID</th><th style="width:32%;">Title</th><th style="width:38%;">Last 10 Results</th><th style="width:16%;">Score</th></tr>
    </thead>
    <tbody>
      ${data.flakyTCs.slice(0, 5).map(tc => {
        const scoreColor = tc.flakyScore >= 70 ? 'rgb(239,68,68)' : tc.flakyScore >= 50 ? 'rgb(249,115,22)' : 'rgb(15,23,42)';
        const dots = (tc.lastTenResults || []).slice(0, 10).map(r =>
          r === 'passed'
            ? `<span class="dot dot-pass"></span>`
            : `<span class="dot dot-fail"></span>`
        ).join('');
        return `
      <tr>
        <td style="font-size:9px;">${e((tc.id || '').slice(0, 12))}</td>
        <td>${e(tc.title.length > 24 ? tc.title.slice(0, 21) + '...' : tc.title)}</td>
        <td>${dots}</td>
        <td style="font-weight:700;color:${scoreColor};">${tc.flakyScore}% (${e(tc.frequency)})</td>
      </tr>`;
      }).join('')}
    </tbody>
  </table>` : ''}

  <div class="sec-title">Coverage Gaps</div>
  ${data.coverageGaps.length === 0 ? `
  <div style="background:rgb(236,253,245);border:1px solid rgb(16,163,127);border-radius:6px;padding:12px 16px;display:flex;align-items:center;gap:10px;">
    <span style="font-size:14px;">✓</span>
    <span style="font-size:11px;color:rgb(15,23,42);">All modules tested — no coverage gaps detected.</span>
  </div>` : `
  <table class="pdf-table" style="font-size:10px;">
    <thead>
      <tr><th style="width:32%;">Module</th><th style="width:18%;">Untested TCs</th><th style="width:18%;">% of Module</th><th style="width:32%;">Risk</th></tr>
    </thead>
    <tbody>
      ${data.coverageGaps.map(gap => `
      <tr>
        <td style="font-weight:600;">${e(gap.module.length > 22 ? gap.module.slice(0, 19) + '...' : gap.module)}</td>
        <td style="font-weight:600;">${gap.untestedCount}</td>
        <td>${gap.percentOfModule.toFixed(1)}%</td>
        <td>${riskBadge(gap.risk)}</td>
      </tr>`).join('')}
    </tbody>
  </table>`}
</div>

<div class="pdf-footer">
  <span>${e(data.projectName)}</span>
  <span>Generated by Testably — ${today}</span>
  <span>Page ${pageNum} of ${totalPages}</span>
</div>`;
}
