import { PdfData } from '../pdfTypes';
import { e, pctColor, fmtDate } from './htmlUtils';

export function renderPage4(data: PdfData, pageNum: number, totalPages: number): string {
  const today = fmtDate();

  const totalAll = data.statusCounts.passed + data.statusCounts.failed + data.statusCounts.blocked
    + data.statusCounts.retest + data.statusCounts.untested || 1;
  const runSummary = [
    { label: 'Passed', color: 'rgb(16,163,127)', count: data.statusCounts.passed },
    { label: 'Failed', color: 'rgb(239,68,68)', count: data.statusCounts.failed },
    { label: 'Blocked', color: 'rgb(249,115,22)', count: data.statusCounts.blocked },
    { label: 'Retest', color: 'rgb(234,179,8)', count: data.statusCounts.retest },
    { label: 'Untested', color: 'rgb(203,213,225)', count: data.statusCounts.untested },
  ];

  const statusClass = (s: string) => {
    const l = (s || '').toLowerCase();
    if (l === 'passed') return 'c-pass';
    if (l === 'failed') return 'c-fail';
    if (l === 'blocked') return 'c-block';
    if (l === 'retest') return 'c-retest';
    return 'c-light';
  };

  return `
<div class="pdf-header">
  <span class="logo">Testably</span>
  <span class="page-title">Execution Detail</span>
</div>

<div class="pdf-content">
  <div class="sec-title" style="margin-top:0;">Run Summary</div>
  <div style="background:rgb(248,250,252);border:1px solid rgb(226,232,240);border-radius:8px;padding:10px 18px;display:flex;justify-content:space-around;align-items:center;margin-bottom:14px;">
    ${runSummary.map((s, i) => `
    ${i > 0 ? '<span style="border-left:1px solid rgb(226,232,240);height:32px;"></span>' : ''}
    <div style="text-align:center;">
      <div style="font-size:9px;color:rgb(100,116,139);">${s.label}</div>
      <div style="font-size:16px;font-weight:700;color:${s.color};">${s.count}</div>
      <div style="font-size:9px;color:rgb(100,116,139);">${(s.count / totalAll * 100).toFixed(1)}%</div>
    </div>`).join('')}
  </div>

  <div class="sec-title">Run Results</div>
  <table class="pdf-table" style="margin-bottom:14px;font-size:10px;">
    <thead>
      <tr>
        <th style="width:4%;">#</th>
        <th style="width:22%;">Run Name</th>
        <th style="width:16%;">Milestone</th>
        <th style="width:10%;">Status</th>
        <th style="width:7%;">Pass</th>
        <th style="width:7%;">Fail</th>
        <th style="width:7%;">Blk</th>
        <th style="width:9%;">Total</th>
        <th style="width:9%;">Rate%</th>
      </tr>
    </thead>
    <tbody>
      ${data.runResults.slice(0, 10).map((r, i) => `
      <tr>
        <td class="c-light">${i + 1}</td>
        <td style="max-width:140px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">${e(r.runName.length > 20 ? r.runName.slice(0, 17) + '...' : r.runName)}</td>
        <td style="font-size:9px;color:rgb(100,116,139);">${e(r.milestone.length > 14 ? r.milestone.slice(0, 11) + '...' : r.milestone)}</td>
        <td><span class="${statusClass(r.status)}" style="font-weight:600;font-size:9px;">${e(r.status)}</span></td>
        <td class="c-pass" style="font-weight:600;">${r.passed}</td>
        <td class="c-fail">${r.failed}</td>
        <td class="c-block">${r.blocked}</td>
        <td style="font-weight:600;">${r.total}</td>
        <td style="font-weight:700;color:${pctColor(r.passRate)};">${r.passRate.toFixed(1)}%</td>
      </tr>`).join('')}
    </tbody>
  </table>

  <div class="sec-title">Module Coverage</div>
  <table class="pdf-table" style="font-size:10px;">
    <thead>
      <tr>
        <th style="width:26%;">Module</th>
        <th style="width:8%;">TCs</th>
        <th style="width:8%;">Tested</th>
        <th style="width:8%;">Untested</th>
        <th style="width:10%;">Pass%</th>
        <th style="width:40%;">Coverage Bar</th>
      </tr>
    </thead>
    <tbody>
      ${data.folderCoverage.slice(0, 10).map(f => {
        return `
      <tr>
        <td style="font-weight:600;">${e(f.folder.length > 20 ? f.folder.slice(0, 17) + '...' : f.folder)}</td>
        <td>${f.totalTCs}</td>
        <td>${f.tested}</td>
        <td class="c-light">${f.untested}</td>
        <td style="font-weight:700;color:${pctColor(f.passRate)};">${f.passRate.toFixed(1)}%</td>
        <td>
          <div class="prog-bar" style="width:140px;">
            <div class="prog-fill" style="width:${f.passRate.toFixed(1)}%;background:${pctColor(f.passRate)};"></div>
          </div>
        </td>
      </tr>`;
      }).join('')}
    </tbody>
  </table>
</div>

<div class="pdf-footer">
  <span>${e(data.projectName)}</span>
  <span>Generated by Testably — ${today}</span>
  <span>Page ${pageNum} of ${totalPages}</span>
</div>`;
}
