import { useState } from 'react';
import { supabase } from '../../../lib/supabase';
import type { Requirement, RequirementPriority, RequirementStatus } from '../../../types/rtm';
import { ModalShell } from '../../../components/ModalShell';

const fieldCls = `w-full border border-slate-200 rounded-lg text-sm text-slate-700 px-3 py-2 bg-white focus:outline-none focus:border-indigo-400 focus:shadow-[0_0_0_3px_rgba(99,102,241,0.1)] transition-colors`;
const labelCls = `block text-xs font-semibold text-slate-600 mb-1`;

interface Props {
  projectId: string;
  requirement: Requirement | null;
  onClose: () => void;
  onSaved: () => void;
}

export default function RequirementModal({ projectId, requirement, onClose, onSaved }: Props) {
  const isEdit = !!requirement;

  const [title, setTitle] = useState(requirement?.title || '');
  const [description, setDescription] = useState(requirement?.description || '');
  const [priority, setPriority] = useState<RequirementPriority>(requirement?.priority || 'P3');
  const [category, setCategory] = useState(requirement?.category || '');
  const [status, setStatus] = useState<RequirementStatus>(requirement?.status || 'active');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) { setError('Title is required.'); return; }
    setSaving(true);
    setError(null);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      if (isEdit) {
        const { error: err } = await supabase
          .from('requirements')
          .update({ title: title.trim(), description: description.trim() || null, priority, category: category.trim() || null, status, updated_at: new Date().toISOString() })
          .eq('id', requirement.id);
        if (err) throw err;
      } else {
        const { error: err } = await supabase
          .from('requirements')
          .insert({
            project_id: projectId,
            title: title.trim(),
            description: description.trim() || null,
            priority,
            category: category.trim() || null,
            status,
            source: 'manual',
            created_by: user.id,
            // custom_id is auto-generated by DB trigger
          });
        if (err) throw err;
      }
      onSaved();
    } catch (err: any) {
      setError(err.message || 'Failed to save requirement.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <ModalShell onClose={onClose}>
      <div
        style={{
          width: '100%',
          maxWidth: '36rem',
          background: '#fff',
          borderRadius: '0.875rem',
          boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
          overflow: 'hidden',
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '1rem 1.25rem', borderBottom: '1px solid #E2E8F0' }}>
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-indigo-50 flex items-center justify-center">
              <i className="ri-git-branch-line text-indigo-600 text-sm" />
            </div>
            <h2 style={{ fontSize: '0.9375rem', fontWeight: 600, color: '#0F172A' }}>
              {isEdit ? `Edit ${requirement.custom_id}` : 'New Requirement'}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="w-7 h-7 flex items-center justify-center rounded-md text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
          >
            <i className="ri-close-line text-lg" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit}>
          <div style={{ padding: '1.25rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {/* Title */}
            <div>
              <label className={labelCls}>Title <span className="text-red-400">*</span></label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className={fieldCls}
                placeholder="e.g. User can log in with email and password"
                autoFocus
                maxLength={500}
              />
            </div>

            {/* Description */}
            <div>
              <label className={labelCls}>Description</label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className={fieldCls}
                placeholder="Detailed requirement description..."
                rows={4}
                style={{ resize: 'vertical', minHeight: '5rem' }}
              />
            </div>

            {/* Priority + Status */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
              <div>
                <label className={labelCls}>Priority</label>
                <select value={priority} onChange={(e) => setPriority(e.target.value as RequirementPriority)} className={fieldCls}>
                  <option value="P1">P1 – Critical</option>
                  <option value="P2">P2 – High</option>
                  <option value="P3">P3 – Medium</option>
                  <option value="P4">P4 – Low</option>
                </select>
              </div>
              <div>
                <label className={labelCls}>Status</label>
                <select value={status} onChange={(e) => setStatus(e.target.value as RequirementStatus)} className={fieldCls}>
                  <option value="draft">Draft</option>
                  <option value="active">Active</option>
                  <option value="deprecated">Deprecated</option>
                </select>
              </div>
            </div>

            {/* Category */}
            <div>
              <label className={labelCls}>Category <span className="text-slate-400 font-normal">(optional)</span></label>
              <input
                type="text"
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                className={fieldCls}
                placeholder="e.g. Authentication, Payment, Security..."
                maxLength={100}
              />
            </div>

            {error && (
              <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-red-50 border border-red-100 text-red-600 text-xs">
                <i className="ri-error-warning-line" />
                {error}
              </div>
            )}
          </div>

          {/* Footer */}
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem', padding: '0.875rem 1.25rem', borderTop: '1px solid #E2E8F0', background: '#F8FAFC' }}>
            <button
              type="button"
              onClick={onClose}
              style={{ padding: '0.4375rem 0.875rem', borderRadius: '0.5rem', fontSize: '0.8125rem', fontWeight: 500, color: '#374151', background: '#fff', border: '1px solid #E2E8F0', cursor: 'pointer' }}
              className="hover:bg-slate-50 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving || !title.trim()}
              style={{
                padding: '0.4375rem 1rem',
                borderRadius: '0.5rem',
                fontSize: '0.8125rem',
                fontWeight: 600,
                color: '#fff',
                background: saving || !title.trim() ? '#A5B4FC' : '#6366F1',
                border: 'none',
                cursor: saving || !title.trim() ? 'not-allowed' : 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '0.375rem',
              }}
            >
              {saving && <i className="ri-loader-4-line animate-spin" />}
              {isEdit ? 'Save changes' : 'Create Requirement'}
            </button>
          </div>
        </form>
      </div>
    </ModalShell>
  );
}
