import { jsPDF } from 'jspdf';
import { PdfConfig } from './pdfTypes';

export function getDefaultConfig(): PdfConfig {
  return {
    primaryColor: [99, 102, 241],
    successColor: [16, 163, 127],
    failureColor: [239, 68, 68],
    warningColor: [249, 115, 22],
    restColor: [234, 179, 8],
    inactiveColor: [203, 213, 225],
    textDark: [15, 23, 42],
    textLight: [100, 116, 139],
    bgLight: [248, 250, 252],
    borderColor: [226, 232, 240],
    criticalColor: [239, 68, 68],
    highColor: [245, 158, 11],
    mediumColor: [99, 102, 241],
    lowColor: [148, 163, 184],
    font: 'helvetica',
    pageWidth: 210,
    pageHeight: 297,
    margin: 20,
    contentWidth: 170,
    headerHeight: 14,
    footerY: 287,
    separatorY: 285,
  };
}

export function drawHeader(pdf: jsPDF, title: string, config: PdfConfig): void {
  pdf.setFillColor(...config.primaryColor);
  pdf.rect(0, 0, config.pageWidth, 14, 'F');
  pdf.setFont(config.font, 'bold');
  pdf.setFontSize(10);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Testably', config.margin, 9);
  pdf.setFont(config.font, 'normal');
  pdf.setFontSize(9);
  pdf.text(title, config.pageWidth - config.margin, 9, { align: 'right' });
}

export function drawCoverHeader(pdf: jsPDF, projectName: string, config: PdfConfig): void {
  pdf.setFillColor(...config.primaryColor);
  pdf.rect(0, 0, config.pageWidth, 40, 'F');
  pdf.setFont(config.font, 'bold');
  pdf.setFontSize(10);
  pdf.setTextColor(255, 255, 255);
  pdf.text('Testably', config.margin, 8);
  pdf.setFontSize(18);
  const safeName = String(projectName || 'Project');
  pdf.text(safeName, config.margin, 24, { maxWidth: 150 });
  pdf.setFontSize(11);
  pdf.setFont(config.font, 'normal');
  pdf.text('Quality Executive Report', config.margin, 32);
  pdf.setFontSize(8);
  const generatedDate = new Date().toISOString().split('T')[0];
  pdf.text(`Report Generated: ${generatedDate}`, config.pageWidth - config.margin, 8, { align: 'right' });
}

export function drawFooter(pdf: jsPDF, pageNum: number, totalPages: number,
  projectName: string, config: PdfConfig): void {
  pdf.setDrawColor(...config.borderColor);
  pdf.setLineWidth(0.3);
  pdf.line(config.margin, config.separatorY, config.pageWidth - config.margin, config.separatorY);
  pdf.setFont(config.font, 'normal');
  pdf.setFontSize(8);
  pdf.setTextColor(...config.textLight);
  pdf.text(String(projectName || ''), config.margin, config.footerY);
  const generatedDate = new Date().toISOString().split('T')[0];
  pdf.text(`Generated by Testably — ${generatedDate}`, config.pageWidth / 2, config.footerY, { align: 'center' });
  pdf.text(`Page ${pageNum} of ${totalPages}`, config.pageWidth - config.margin, config.footerY, { align: 'right' });
}

export function drawSectionTitle(pdf: jsPDF, title: string, x: number, y: number, config: PdfConfig): void {
  pdf.setFont(config.font, 'bold');
  pdf.setFontSize(11);
  pdf.setTextColor(...config.textDark);
  pdf.text(title, x, y);
}

export function drawKpiCard(pdf: jsPDF, x: number, y: number, width: number,
  height: number, label: string, value: string,
  config: PdfConfig,
  opts?: { delta?: string; deltaPositive?: boolean; sub?: string; valueColor?: [number, number, number] }): void {
  pdf.setFillColor(...config.bgLight);
  pdf.setDrawColor(...config.borderColor);
  pdf.setLineWidth(0.5);
  pdf.roundedRect(x, y, width, height, 2, 2, 'FD');

  pdf.setFont(config.font, 'normal');
  pdf.setFontSize(7);
  pdf.setTextColor(...config.textLight);
  pdf.text(label, x + 3, y + 5);

  pdf.setFont(config.font, 'bold');
  pdf.setFontSize(16);
  const vc = opts?.valueColor || config.textDark;
  pdf.setTextColor(...vc);
  pdf.text(String(value || '-'), x + 3, y + 14);

  if (opts?.delta) {
    pdf.setFont(config.font, 'normal');
    pdf.setFontSize(8);
    const deltaColor = opts.deltaPositive !== false ? config.successColor : config.failureColor;
    pdf.setTextColor(...deltaColor);
    pdf.text(opts.delta, x + width - 3, y + 5, { align: 'right' });
  }
  if (opts?.sub) {
    pdf.setFont(config.font, 'normal');
    pdf.setFontSize(7);
    pdf.setTextColor(...config.textLight);
    pdf.text(opts.sub, x + 3, y + height - 2);
  }
}

export function drawTable(pdf: jsPDF, x: number, y: number, headers: string[],
  rows: (string | number)[][], columnWidths: number[], config: PdfConfig,
  options?: { rowHeight?: number; headerBgColor?: [number, number, number]; zebra?: boolean; maxRows?: number }): number {
  const opts = {
    rowHeight: 7,
    headerBgColor: config.primaryColor as [number, number, number],
    zebra: true,
    maxRows: rows.length,
    ...options,
  };
  const totalW = columnWidths.reduce((a, b) => a + b, 0);
  let currentY = y;

  pdf.setFillColor(...opts.headerBgColor);
  pdf.rect(x, currentY, totalW, 7, 'F');
  pdf.setFont(config.font, 'bold');
  pdf.setFontSize(8);
  pdf.setTextColor(255, 255, 255);
  let headerX = x;
  headers.forEach((header, i) => {
    pdf.text(header, headerX + 2, currentY + 5, { maxWidth: columnWidths[i] - 4 });
    headerX += columnWidths[i];
  });
  currentY += 7;

  const displayRows = rows.slice(0, opts.maxRows);
  displayRows.forEach((row, rowIndex) => {
    if (opts.zebra && rowIndex % 2 === 0) {
      pdf.setFillColor(...config.bgLight);
      pdf.rect(x, currentY, totalW, opts.rowHeight, 'F');
    }
    pdf.setDrawColor(...config.borderColor);
    pdf.setLineWidth(0.2);
    pdf.line(x, currentY + opts.rowHeight, x + totalW, currentY + opts.rowHeight);
    pdf.setFont(config.font, 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(...config.textDark);
    let cellX = x;
    row.forEach((cell, colIndex) => {
      pdf.text(String(cell ?? ''), cellX + 2, currentY + opts.rowHeight - 2, { maxWidth: columnWidths[colIndex] - 4 });
      cellX += columnWidths[colIndex];
    });
    currentY += opts.rowHeight;
  });
  return currentY;
}

export function drawProgressBar(pdf: jsPDF, x: number, y: number, width: number,
  height: number, percentage: number, fillColor: [number, number, number], config: PdfConfig): void {
  const radius = height / 2;
  pdf.setFillColor(...config.bgLight);
  pdf.setDrawColor(...config.borderColor);
  pdf.setLineWidth(0.3);
  pdf.roundedRect(x, y, width, height, radius, radius, 'FD');
  const fillWidth = Math.min((Math.max(percentage, 0) / 100) * width, width);
  if (fillWidth > 0) {
    pdf.setFillColor(...fillColor);
    pdf.setDrawColor('none' as any);
    pdf.roundedRect(x, y, fillWidth, height, radius, radius, 'F');
  }
  pdf.setFont(config.font, 'bold');
  pdf.setFontSize(7);
  pdf.setTextColor(...config.textDark);
  pdf.text(`${Math.round(percentage)}%`, x + width / 2, y + height / 2 + 1, { align: 'center' });
}

export function drawStackedBar(pdf: jsPDF, x: number, y: number, width: number,
  height: number, segments: Array<{ count: number; color: [number, number, number] }>): void {
  const totalCount = segments.reduce((sum, seg) => sum + seg.count, 0);
  if (totalCount === 0) return;
  const radius = height / 2;
  let currentX = x;
  segments.forEach((segment, index) => {
    const segmentWidth = (segment.count / totalCount) * width;
    if (segmentWidth <= 0) return;
    pdf.setFillColor(...segment.color);
    if (index === 0) {
      pdf.roundedRect(currentX, y, segmentWidth, height, radius, 0, 'F');
    } else if (index === segments.length - 1) {
      pdf.roundedRect(currentX, y, segmentWidth, height, 0, radius, 'F');
    } else {
      pdf.rect(currentX, y, segmentWidth, height, 'F');
    }
    currentX += segmentWidth;
  });
}

export function drawRoundedBox(pdf: jsPDF, x: number, y: number, width: number,
  height: number, bgColor: [number, number, number], borderColor: [number, number, number],
  radius: number = 2, lineWidth: number = 0.5): void {
  pdf.setFillColor(...bgColor);
  pdf.setDrawColor(...borderColor);
  pdf.setLineWidth(lineWidth);
  pdf.roundedRect(x, y, width, height, radius, radius, 'FD');
}

export function formatDateShort(dateStr: string): string {
  try {
    const date = new Date(dateStr);
    const monthShort = date.toLocaleString('en-US', { month: 'short' });
    return `${monthShort} ${date.getDate()}`;
  } catch {
    return '-';
  }
}

export function formatRelativeTime(date: Date | string): string {
  try {
    const then = new Date(date);
    const now = new Date();
    const diffMs = now.getTime() - then.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMins / 60);
    const diffDays = Math.floor(diffHours / 24);
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;
    return `${Math.floor(diffDays / 7)}w ago`;
  } catch {
    return '-';
  }
}

export function getPercentageColor(percentage: number, config: PdfConfig): [number, number, number] {
  if (percentage >= 90) return config.successColor;
  if (percentage >= 70) return config.warningColor;
  return config.failureColor;
}

export function getPriorityColor(priority: string, config: PdfConfig): [number, number, number] {
  switch ((priority || '').toLowerCase()) {
    case 'critical': return config.criticalColor;
    case 'high': return config.highColor;
    case 'medium': return config.mediumColor;
    default: return config.lowColor;
  }
}

export function getPriorityAbbr(priority: string): string {
  const p = (priority || '').toLowerCase();
  if (p === 'critical') return 'Crit';
  if (p === 'high') return 'High';
  if (p === 'medium') return 'Med';
  return 'Low';
}

export function safeText(val: any): string {
  if (val === null || val === undefined) return '-';
  return String(val);
}
